### ISSUE TITLE
Task 1C fails after downloading the dataset

### ISSUE THREAD

**Issue by dangpzanco** [toni-heittola/dcase2019_task1_baseline#1]
#### Description

Error when running `python task1c.py`. Task 1A worked just fine and produced similar results.

#### Expected Results

Expected Task 1C to download the dataset (it did), extract features, normalize, train, test and evaluate.

#### Actual Results

```
root@1e8de6cd35a5:~/dcase2019_task1_baseline# python task1c.py 
[I] DCASE2019 / Task1C -- Acoustic scene classification
[I] 
Download packages        :  62%|#####7   | 8/13 [19:08<14:35, 175.03s/it^
[E] Dataset errors:                                                                                                                         
FOLD[1]          TRAIN SET     Empty set                                                                                                    
FOLD[1]          TEST SET      Empty set
FOLD[1]          EVAL SET    Empty set              	(datasets.py:1326)
NoneType: None
[E] Uncaught exception 	(logging.py:221)
Traceback (most recent call last):
  File "task1c.py", line 1105, in <module>
    sys.exit(main(sys.argv))
  File "task1c.py", line 125, in main
    data_path=param.get_path('path.dataset'),
  File "/mnt/dsp/miniconda3/lib/python3.6/site-packages/dcase_util/datasets/datasets.py", line 688, in initialize
    self.check_metadata()
  File "/mnt/dsp/miniconda3/lib/python3.6/site-packages/dcase_util/datasets/datasets.py", line 1327, in check_metadata
    raise ValueError(message)
ValueError: Dataset errors:
FOLD[1]          TRAIN SET     Empty set
FOLD[1]          TEST SET      Empty set
FOLD[1]          EVAL SET    Empty set   
```

#### Versions

```
Linux-4.15.0-39-generic-x86_64-with-debian-buster-sid
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
NumPy 1.16.2
SciPy 1.2.1
Matplotlib 3.0.2
librosa 0.6.2
keras 2.2.4
tensorflow 1.12.0
dcase_util 0.2.5
sed_eval 0.2.1
```

PS: `dcase_util` reports version `0.2.5`, but the latest version (`0.2.6`) is installed.

**Comment by toni-heittola** [comment]
Dataset was missing evaluation setup files, and this caused the error. The dataset has been now updated into version 2, which contains the required files. Version 2 of the dataset can be accessed here > https://zenodo.org/record/2591503
At the same time, dcase_utils has been updated also into version 0.2.7 to download correct dataset version.

To correct this for your baseline setup:

1. Update dcase_util into version 0.2.7 `pip install dcase_util --upgrade`
2. Remove file `dcase2019_task1_baseline/datasets/TAU-urban-acoustic-scenes-2019-openset-development/TAU-urban-acoustic-scenes-2019-openset-development.meta.zip`
3. Restart system to download new meta data `./task1c.py`

Did this fix the problem?

**Comment by dangpzanco** [comment]
Yes, it did fix the problem. Thank you very much for the fast reply and the corrections.
